default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

development:
  <<: *default
  database: <%= Rails.application.class.module_parent_name.underscore %>_development

test:
  <<: *default
  database: <%= Rails.application.class.module_parent_name.underscore %>_test

production:
  <<: *default
  database: <%= Rails.application.class.module_parent_name.underscore %>_production
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
